fix: fix missing field  in shared string
```
thread 'main' panicked at 'workbook shared strings error: XmlDeError(Custom("missing field `t`"))', ..../src/document/spreadsheet/mod.rs:71:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```